CONFIG_LOG_MAX_LEVEL=3
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=900000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_POINTER_2S_MIXER_ENSURE_SYNC=y
CONFIG_ZMK_ADAPTIVE_FEEDBACK=n
CONFIG_ZMK_ADAPTIVE_FEEDBACK_SHELL=n
CONFIG_ZMK_FEEDBACK_COMMON=n
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE=n
CONFIG_SHELL_BACKEND_SERIAL=n
CONFIG_LED_STRIP=y
