CONFIG_LOG_MAX_LEVEL=3
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=2700000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=2700000
CONFIG_POINTER_2S_MIXER_ENSURE_SYNC=y
# Composite scanner driver is selected automatically from buttons.dtsi.
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=15
CONFIG_ANKUR_RGB_PRESENT=y
CONFIG_ZMK_ADAPTIVE_FEEDBACK_MAX_COLORS=7
CONFIG_ZMK_FEEDBACK_COMMON=y
