name: ankurs-customised-endgame-debug

on:
  push:
    branches: [ankurs-customised-endgame-firmware]
  workflow_dispatch:

jobs:
  firmware:
    uses: ./.github/workflows/ankur-build.yml
    with:
      build_name: ankurs-customised-endgame-debug
      snippets: studio-rpc-usb-uart zmk-usb-logging
