name: ankurs customised endgame firmware production
run-name: ankurs customised endgame firmware production

on:
  push:
    branches: [ankurs-customised-endgame-firmware]
  workflow_dispatch:

jobs:
  firmware:
    uses: ./.github/workflows/ankur-build.yml
    with:
      build_name: ankurs-customised-endgame-production
      snippets: studio-rpc-usb-uart ankur-production
