name: 18 SEPT CODE IMPROVEMENTS
run-name: 18 SEPT CODE IMPROVEMENTS

on:
  push:
    branches: [ankurs-customised-endgame-firmware]
  workflow_dispatch:

jobs:
  firmware:
    uses: ./.github/workflows/ankur-build.yml
    with:
      build_name: ankurs-customised-endgame-production
      snippets: studio-rpc-usb-uart ankur-production
      build_kind: production
